#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This file is part of the VOH Project

"""
VOH is a Verilog package manager based on GitHub.
"""

__author__ = 'Jesús Arroyo Torrens'
__email__ = 'jesus.arroyo@bq.com'
__license__ = 'GPLv2'
__version__ = '0.0.1'


def parse_arguments():
    import argparse
    description = "VOH. Verilog Open Hardware package manager."
    parser = argparse.ArgumentParser(description=description)

    # Add dependency parameters
    parser.add_argument("user", help="GitHub user's name")
    parser.add_argument("repo", help="GitHub repository's name")

    # Parse the arguments
    args = parser.parse_args()

    # Return the user and the repo
    return args.user, args.repo


def check_repository(user, repo):
    import urllib2
    try:
        # Try to connect to the repository
        urllib2.urlopen("https://github.com/" + user + "/" + repo)
        return True
    except urllib2.HTTPError, e:
        print("Error: " + str(e.code))
        return False
    except urllib2.URLError, e:
        print("Error: " + str(e.args))
        return False


def git_clone(user, repo):
    # Create voh_modules dir
    import os
    path = os.path.join(os.getcwd(), "voh_modules")
    if not os.path.exists(path):
        os.makedirs(path)

    # Clone repository
    from git import Repo
    Repo.clone_from("https://github.com/" + user + "/" + repo + ".git",
                    os.path.join(path, repo))


if __name__ == '__main__':

    # Parse arguments
    user, repo = parse_arguments()

    # Check repository
    if check_repository(user, repo):

        # Git clone repository
        git_clone(user, repo)
